name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:17-alpine3.12
    steps: #steps will run in container, not runner VM
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release