name: matrix
on: pull_request

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [6, 8, 10]
        include: # This would add another node_version ONLY when os=ubuntu-latest
          - os: ubuntu-latest
            node_version: 4
            is_ubuntu_8: "true"
        exclude: #This block will prevent running the job when os=ubuntu-latest & node_version=6 or os=macos-latest & node_version=8
          - os: ubuntu-latest
            node_version: 6
          - os: macos-latest
            node_version: 8
    runs-on: ${{ matrix.os }}
    env:
      IS_UBUNTU_8: ${{ matrix.is_ubuntu_8 }}
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Log node version
        run: | 
          node -v
          echo $IS_UBUNTU_8